name: LAMP deploy to AWS

on:
  workflow_dispatch:

jobs:
  infrastructure:
    name: Building infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform-config init
      
      - name: Terraform Apply
        run: terraform -chdir=terraform-config apply -auto-approve

      - name: Upload tfstate file
        uses: actions/upload-artifact@v3
        with:
          name: terraform.tfstate
          path: terraform-config/terraform.tfstate

      - name: Installing Ansible
        run: |
          sudo apt update -y
          sudo apt install software-properties-common -y
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible -y

      - name: Making inventory file
        run: |
          sed -i "s/ubuntu-server-1-address/`terraform output -raw webserver-1-public-ip`/" ansible-config/inventory.yml
          sed -i "s/ubuntu-server-2-address/`terraform output -raw webserver-2-public-ip`/" ansible-config/inventory.yml

      - name: Ansible Ping
        run: |
          ansible webservers -i ansible-config/inventory.yml -m ping
      
